In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model, svm
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import graphviz 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.svm import SVC

#load datasets
wine = datasets.load_wine()
df = pd.DataFrame(wine.data)
y = wine.target
z = wine.data







In [2]:
#split the training and test sets
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)
print ("Dimensions of the Training Data Set are: \n",X_train.shape, y_train.shape,"\n")
print ("Dimensions of the Test Data Set are: \n",X_test.shape, y_test.shape,"\n")



Dimensions of the Training Data Set are: 
 (142, 13) (142,) 

Dimensions of the Test Data Set are: 
 (36, 13) (36,) 



In [3]:
#Selecting Two Attributes for training and testing sets
best2 = SelectKBest(score_func=chi2, k=2)
best2.fit(X_train, y_train)
best2_attributes = best2.get_support(indices = True)
extracted2 = [df.columns[iterator] for iterator in best2_attributes]
X_train = X_train[extracted2]
X_test = X_test[extracted2]

In [4]:
print ("\n The shape of the extracted train set features are: \n",X_train.shape)
print ("\n The shape of the extracted test set  features are: \n",X_test.shape)




 The shape of the extracted train set features are: 
 (142, 2)

 The shape of the extracted test set  features are: 
 (36, 2)


In [5]:
######################### SVM Gaussian RBF ################################
#Building a SVM model with Kernal = 'Gaussian RBF'
svclassifier_rbf = SVC(kernel='rbf', decision_function_shape = 'ovo')  
svclassifier_rbf.fit(X_train, y_train) 


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
#Prediction using SVM Gaussian RBF
y_pred_rbf = svclassifier_rbf.predict(X_test)


In [7]:
#Calculating the confusion matrix and the classification Report.
print("\n The confusion Matrix for the SVM  Gaussian RBF Kernal is: \n", confusion_matrix(y_test,y_pred_rbf))  
print("\n The classification Report for the SVM Gaussian RBF Kernal is: \n",classification_report(y_test,y_pred_rbf))



 The confusion Matrix for the SVM  Gaussian RBF Kernal is: 
 [[ 3  6  0]
 [ 0 15  1]
 [ 1  9  1]]

 The classification Report for the SVM Gaussian RBF Kernal is: 
              precision    recall  f1-score   support

          0       0.75      0.33      0.46         9
          1       0.50      0.94      0.65        16
          2       0.50      0.09      0.15        11

avg / total       0.56      0.53      0.45        36

